### PR TITLE
Add forms

### PR DESCRIPTION
**Pull request by AnselemOdims**
# Steps taken to complete this milestone
- Added the `comments` button
- Added the `like` button
- Included the `create post` button
- Added routes for `new` and `create` actions of `post`
- Created `new` and `create` methods in the `PostsController`
- Added form for creating new post
- Added routes for `new` and `create` actions of `comment`
- Created `new` and `create` methods in the `CommentsController`
- Created routes for `likes`
- Styled the `forms` and `pages`

#### New Post Form
image

#### Comment Form
image

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @AnselemOdims,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**
- Linters are passing👌
- The PR is good 👌 


## Required Changes ♻️
_Check the comments under the review._

- Hello @AnselemOdims and congratulations on your app however, the `rename tables` to change the `user_id` to `author_id` is causing an error because it does not exist the `user_id`.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- The **readme** file in the **Getting started section** is missing directions on how to start the database and create it and migrate the database. 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AnselemOdims** [comment]
I am not sure I completely understand the feedback. Can you elaborate?

**Comment by dasileker** [comment]
Hello, on the migration it rendre an error in your change foreign keys tables, and to be specific the user_id in those tables are causing issue because user_id it does not exist.

**Review by Emmyn5600 — APPROVED** [review]
Hi @AnselemOdims

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada: :clap: :clap: :100:

nodding-yes

## Optional suggestions

- [ ] N/A

#### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!:clap::clap::clap:
#### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
#### _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Pull request merged**
